#!/usr/bin/env pwsh
#Requires -Version 7.4
<#
.SYNOPSIS
    Fast inner-loop deploy: build and push a Debug image, then roll it out through ArgoCD.
.DESCRIPTION
    Builds a Debug image with local sibling dependencies, optionally packages its
    umbrella chart, and patches a GitOps ApplicationSet manifest. Deployment-specific
    defaults can be stored in the gitignored deploy.local.psd1 file; explicit command
    line parameters override those defaults.

    The mutable latest-dev image tag requires a unique pod annotation to force a
    rollout. The script updates the shared annotation and every alias-local
    podAnnotations map so workloads with additional network annotations also roll.
.PARAMETER DeployConfigPath
    Local PowerShell data file containing default parameter values.
.PARAMETER Tag
    Container image tag to deploy.
.PARAMETER Platforms
    Docker target platforms forwarded to build.ps1.
.PARAMETER ManifestRepo
    Root path of the caller-supplied GitOps repository.
.PARAMETER ManifestPath
    ApplicationSet manifest path relative to ManifestRepo.
.PARAMETER ImageRepository
    Container image repository written to the ApplicationSet values.
.PARAMETER SkipBuild
    Skips the image build and re-rolls the existing image tag.
.PARAMETER NoCommit
    Patches files locally without committing or pushing the GitOps repository.
.PARAMETER SkipMigrationCheck
    Skips the optional EF model-drift validation.
.PARAMETER Chart
    Packages and publishes the application umbrella chart.
.PARAMETER OnlyCharts
    Deploys only the dashboard chart. The legacy OnlyDashboards alias is accepted.
.PARAMETER ChartPath
    Application chart path relative to the repository root.
.PARAMETER ChartRegistry
    OCI registry hosting the chart.
.PARAMETER ChartRepository
    OCI repository for the application chart.
.PARAMETER DashboardChartPath
    Dashboard chart path relative to the repository root.
.PARAMETER DashboardChartRepository
    OCI repository for the dashboard chart.
.PARAMETER DashboardManifestPath
    Dashboard ApplicationSet manifest path relative to ManifestRepo.
.PARAMETER ChartVersion
    Chart version override. A timestamped development version is generated by default.
.PARAMETER DeploymentName
    Deployment name used in temporary paths and commit messages.
.PARAMETER PodAnnotationName
    Pod annotation key updated with a unique deployment stamp to force rollout.
.PARAMETER MigrationProject
    Optional EF project path used for model-drift validation.
.PARAMETER MigrationContext
    Optional EF DbContext name used for model-drift validation.
.PARAMETER MigrationConnectionStringEnvironmentVariable
    Environment variable temporarily populated for model-drift validation.
.PARAMETER MigrationConnectionString
    Connection string value used only by the optional model-drift validation.
.PARAMETER Rest
    Remaining arguments forwarded to build.ps1 after deploy-only validation.
.EXAMPLE
    ./deploy.ps1
.EXAMPLE
    ./deploy.ps1 -ManifestRepo <path-to-gitops-repo> -ManifestPath <manifest-path> -Chart
.EXAMPLE
    ./deploy.ps1 -ManifestRepo <path-to-gitops-repo> -ManifestPath <manifest-path> -SkipBuild -Chart
.EXAMPLE
    ./deploy.ps1 -OnlyCharts -ManifestRepo <path-to-gitops-repo> -DashboardManifestPath <dashboard-manifest-path>
.EXAMPLE
    ./deploy.ps1 -ManifestRepo <path-to-gitops-repo> -ManifestPath <manifest-path> -SkipBuild -NoCommit -WhatIf
.NOTES
    Requires yq and Git. Image, chart, and migration paths additionally require their corresponding tools and credentials.
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$Tag = "latest-dev",
    [string]$Platforms = "linux/arm64",
    [string]$DeployConfigPath = (Join-Path $PSScriptRoot "deploy.local.psd1"),
    [string]$ManifestRepo,
    [string]$ManifestPath,
    [string]$ImageRepository,
    [switch]$SkipBuild,
    [switch]$NoCommit,
    [switch]$SkipMigrationCheck,
    [switch]$Chart,
    [Alias("OnlyDashboards")][switch]$OnlyCharts,
    [string]$ChartPath,
    [string]$ChartRegistry = "ghcr.io",
    [string]$ChartRepository,
    [string]$DashboardChartPath,
    [string]$DashboardChartRepository,
    [string]$DashboardManifestPath,
    [string]$ChartVersion,
    [string]$DeploymentName,
    [string]$PodAnnotationName,
    [string]$MigrationProject,
    [string]$MigrationContext,
    [string]$MigrationConnectionStringEnvironmentVariable,
    [string]$MigrationConnectionString,
    [Parameter(ValueFromRemainingArguments = $true)][string[]]$Rest
)

$ErrorActionPreference = "Stop"
$PSNativeCommandUseErrorActionPreference = $false
Set-StrictMode -Version 3.0

#region Functions
function ConvertTo-DeployBuildArguments {
    [CmdletBinding()]
    [OutputType([string[]])]
    param([AllowEmptyCollection()][string[]]$Arguments)

    $filtered = [System.Collections.Generic.List[string]]::new()
    $argumentsToInspect = @($Arguments | Where-Object { $null -ne $_ })
    for ($index = 0; $index -lt $argumentsToInspect.Count; $index++) {
        $argument = $argumentsToInspect[$index]
        if ($argument -match '^-Configuration(?::(.+))?$') {
            $value = if ($Matches[1]) { $Matches[1] } elseif ($index + 1 -lt $argumentsToInspect.Count) { $argumentsToInspect[++$index] } else { 'Debug' }
            if ($value -ne 'Debug') {
                throw "deploy.ps1 only performs Debug builds; '-Configuration $value' is not supported. Use build.ps1 directly for $value."
            }
            continue
        }
        $filtered.Add($argument)
    }
    return $filtered.ToArray()
}

function Resolve-DeploymentManifestPath {
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [switch]$OnlyCharts,
        [string]$ManifestPath,
        [string]$DashboardManifestPath
    )

    $resolvedPath = if ($OnlyCharts) { $DashboardManifestPath } else { $ManifestPath }
    if ([string]::IsNullOrWhiteSpace($resolvedPath)) {
        $requiredParameter = if ($OnlyCharts) { "DashboardManifestPath" } else { "ManifestPath" }
        throw "-$requiredParameter is required for this deployment mode."
    }
    return $resolvedPath
}

function Get-ManifestPatchExpression {
    [CmdletBinding()]
    [OutputType([string])]
    param([switch]$Chart)

    $assignments = [System.Collections.Generic.List[string]]::new()
    if ($Chart) {
        $assignments.Add('.spec.template.spec.source.targetRevision = strenv(DEPLOY_CHART_VERSION)')
    }
    $assignments.Add('.spec.template.spec.source.helm.valuesObject._shared.image.repository = strenv(DEPLOY_IMG_REPO)')
    $assignments.Add('.spec.template.spec.source.helm.valuesObject._shared.image.tag = strenv(DEPLOY_IMG_TAG)')
    $assignments.Add('.spec.template.spec.source.helm.valuesObject._shared.image.pullPolicy = "Always"')
    $assignments.Add('.spec.template.spec.source.helm.valuesObject._shared.podAnnotations[strenv(DEPLOY_POD_ANNOTATION)] = strenv(DEPLOY_STAMP)')
    $assignments.Add('(.spec.template.spec.source.helm.valuesObject[] | select(has("podAnnotations")).podAnnotations[strenv(DEPLOY_POD_ANNOTATION)]) = strenv(DEPLOY_STAMP)')
    return $assignments -join ' | '
}

function Get-DeploymentGitVersion {
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][string]$RepoRoot)

    if (-not (Get-Command dotnet-gitversion -ErrorAction SilentlyContinue)) {
        Write-Host "dotnet-gitversion not found. Installing GitVersion.Tool globally..." -ForegroundColor Cyan
        dotnet tool install -g GitVersion.Tool
        if ($LASTEXITCODE -ne 0) { throw "Failed to install GitVersion.Tool. Run: dotnet tool install -g GitVersion.Tool" }
        $toolsPath = Join-Path $HOME ".dotnet/tools"
        if ($env:PATH -notlike "*$toolsPath*") { $env:PATH = "$toolsPath$([IO.Path]::PathSeparator)$env:PATH" }
    }
    return "$(dotnet-gitversion $RepoRoot /showvariable FullSemVer)".Trim()
}

function Connect-HelmRegistry {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Registry)

    if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
        throw "gh CLI not found (needed to authenticate Helm to $Registry). Install: https://cli.github.com"
    }
    $ghUser = "$(gh api user --jq .login)".Trim()
    Write-Host "Authenticating Helm to $Registry as $ghUser..." -ForegroundColor Cyan
    gh auth token | helm registry login $Registry --username $ghUser --password-stdin
    if ($LASTEXITCODE -ne 0) { throw "helm registry login $Registry failed." }
}

function Remove-LocalDependencies {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$RepoRoot)

    $dependenciesPath = Join-Path $RepoRoot "deps"
    if (-not (Test-Path -LiteralPath $dependenciesPath)) { return }

    Write-Host "Removing local build dependencies from '$dependenciesPath'..." -ForegroundColor Cyan
    Remove-Item -LiteralPath $dependenciesPath -Recurse -Force
}

function Get-GitUpstream {
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)][string]$Repository,
        [Parameter(Mandatory)][string]$FailureMessage
    )

    $upstream = "$(git -C $Repository rev-parse --abbrev-ref --symbolic-full-name '@{upstream}')".Trim()
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($upstream)) { throw $FailureMessage }
    return $upstream
}

function Get-GitRevision {
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)][string]$Repository,
        [Parameter(Mandatory)][string]$Revision,
        [Parameter(Mandatory)][string]$FailureMessage
    )

    $resolved = "$(git -C $Repository rev-parse $Revision)".Trim()
    if ($LASTEXITCODE -ne 0) { throw $FailureMessage }
    return $resolved
}

function Update-ManifestRepository {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$ManifestRepo)

    $workingTreeChanges = @(git -C $ManifestRepo status --porcelain)
    if ($LASTEXITCODE -ne 0) { throw "git status failed for '$ManifestRepo'." }
    if ($workingTreeChanges.Count -gt 0) {
        throw "GitOps repository '$ManifestRepo' has local changes. Commit, stash, or discard them before deploying."
    }

    Write-Host "Refreshing GitOps repository '$ManifestRepo'..." -ForegroundColor Cyan
    git -C $ManifestRepo fetch --prune
    if ($LASTEXITCODE -ne 0) { throw "git fetch failed for '$ManifestRepo'." }
    $upstream = Get-GitUpstream -Repository $ManifestRepo -FailureMessage "The current GitOps branch has no upstream branch."
    git -C $ManifestRepo merge --ff-only $upstream
    if ($LASTEXITCODE -ne 0) {
        throw "GitOps branch could not be fast-forwarded to '$upstream'. Resolve its branch state before deploying."
    }
}

function Sync-ManifestRepositoryAfterPushFailure {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$ManifestRepo)

    $upstream = Get-GitUpstream -Repository $ManifestRepo -FailureMessage "git push failed and the current GitOps branch has no upstream branch."
    $upstreamBeforeFetch = Get-GitRevision -Repository $ManifestRepo -Revision $upstream -FailureMessage "git push failed and '$upstream' could not be resolved."

    git -C $ManifestRepo fetch --prune
    if ($LASTEXITCODE -ne 0) { throw "git push failed and the GitOps repository could not be refreshed." }
    $upstreamAfterFetch = Get-GitRevision -Repository $ManifestRepo -Revision $upstream -FailureMessage "git push failed and refreshed upstream '$upstream' could not be resolved."
    if ($upstreamBeforeFetch -eq $upstreamAfterFetch) {
        throw "git push failed without '$upstream' advancing; review the push error above."
    }

    Write-Host "Upstream advanced during deployment; rebasing and retrying the push..." -ForegroundColor Yellow
    git -C $ManifestRepo rebase $upstream
    if ($LASTEXITCODE -ne 0) {
        git -C $ManifestRepo rebase --abort
        throw "Automatic GitOps rebase failed. The rebase was aborted; reconcile '$upstream' manually."
    }
}

function Push-ManifestRepository {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$ManifestRepo)

    for ($attempt = 1; $attempt -le 3; $attempt++) {
        git -C $ManifestRepo push
        if ($LASTEXITCODE -eq 0) { return }
        if ($attempt -eq 3) { throw "git push failed after $attempt attempts." }
        Sync-ManifestRepositoryAfterPushFailure -ManifestRepo $ManifestRepo
    }
}

function Assert-NoModelDrift {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$RepoRoot,
        [string]$MigrationProject,
        [string]$MigrationContext,
        [string]$MigrationConnectionStringEnvironmentVariable,
        [string]$MigrationConnectionString
    )

    if ([string]::IsNullOrWhiteSpace($MigrationProject)) { return }
    if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
        throw "dotnet not found - required for the EF model-drift check."
    }
    Write-Host "Checking EF model/migration drift..." -ForegroundColor Cyan
    $previousArtifactsPath = $env:ArtifactsPath
    $previousBaseOutputPath = $env:BaseOutputPath
    $previousConnectionString = if ($MigrationConnectionStringEnvironmentVariable) {
        [Environment]::GetEnvironmentVariable($MigrationConnectionStringEnvironmentVariable)
    }
    $driftOutputPath = Join-Path ([IO.Path]::GetTempPath()) "ef-output-$PID-$([Guid]::NewGuid().ToString('N'))"
    $env:ArtifactsPath = $null
    $env:BaseOutputPath = Join-Path $driftOutputPath "bin\"
    if ($MigrationConnectionStringEnvironmentVariable) {
        [Environment]::SetEnvironmentVariable($MigrationConnectionStringEnvironmentVariable, $MigrationConnectionString)
    }
    $dataProject = Join-Path $RepoRoot $MigrationProject
    Push-Location $RepoRoot
    try {
        dotnet tool restore | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "dotnet tool restore failed (needed for dotnet-ef)." }
        dotnet restore $dataProject | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "dotnet restore failed for the EF model-drift check." }
        $efArguments = @("ef", "migrations", "has-pending-model-changes", "--project", $dataProject, "--startup-project", $dataProject)
        if ($MigrationContext) { $efArguments += @("--context", $MigrationContext) }
        & dotnet @efArguments
        if ($LASTEXITCODE -ne 0) {
            throw "EF model/migration drift check failed. Review the dotnet ef output above; add a migration only when it reports pending model changes."
        }
    }
    finally {
        Pop-Location
        $env:ArtifactsPath = $previousArtifactsPath
        $env:BaseOutputPath = $previousBaseOutputPath
        if ($MigrationConnectionStringEnvironmentVariable) {
            [Environment]::SetEnvironmentVariable($MigrationConnectionStringEnvironmentVariable, $previousConnectionString)
        }
        Remove-Item $driftOutputPath -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function Invoke-DeploymentImageBuild {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$RepoRoot,
        [switch]$SkipBuild,
        [switch]$OnlyCharts,
        [string]$Platforms,
        [string]$Tag,
        [string]$ImageRepository,
        [string[]]$Rest
    )

    if (-not $SkipBuild -and -not $OnlyCharts) {
        & (Join-Path $RepoRoot 'build.ps1') -Push -Configuration Debug -Platforms $Platforms -Tag $Tag @Rest
        if ($LASTEXITCODE -ne 0) { throw "build.ps1 failed with exit code $LASTEXITCODE" }
        return
    }
    if ($OnlyCharts) {
        Write-Host "Skipping image build/push (-OnlyCharts)." -ForegroundColor Yellow
        return
    }
    Write-Host "Skipping build/push (-SkipBuild); re-rolling existing ${ImageRepository}:${Tag}" -ForegroundColor Yellow
}

function Get-DeploymentChart {
    [CmdletBinding()]
    [OutputType([pscustomobject])]
    param(
        [Parameter(Mandatory)][string]$RepoRoot,
        [Parameter(Mandatory)][string]$Timestamp,
        [switch]$OnlyCharts,
        [string]$ChartPath,
        [string]$ChartRepository,
        [string]$DashboardChartPath,
        [string]$DashboardChartRepository,
        [string]$ChartVersion
    )

    if ($OnlyCharts) {
        $ChartPath = $DashboardChartPath
        $ChartRepository = $DashboardChartRepository
    }
    if ([string]::IsNullOrWhiteSpace($ChartPath) -or [string]::IsNullOrWhiteSpace($ChartRepository)) {
        throw "ChartPath and ChartRepository are required for chart deployment. Supply them explicitly or in the deployment configuration."
    }
    if ([string]::IsNullOrWhiteSpace($ChartVersion)) { $ChartVersion = "0.0.0-dev.$Timestamp" }
    $chartDirectory = Join-Path $RepoRoot $ChartPath
    if (-not (Test-Path (Join-Path $chartDirectory 'Chart.yaml'))) {
        throw "Chart not found at '$chartDirectory' (expected Chart.yaml). Pass -ChartPath to override."
    }
    return [pscustomobject]@{
        Path       = $ChartPath
        Repository = $ChartRepository
        Version    = $ChartVersion
        Directory  = $chartDirectory
        Name       = Split-Path $ChartPath -Leaf
    }
}

function Test-DashboardChart {
    [CmdletBinding()]
    param([Parameter(Mandatory)][pscustomobject]$Chart)

    Get-ChildItem (Join-Path $Chart.Directory 'dashboards/*.json') | ForEach-Object {
        try { $null = Get-Content $_.FullName -Raw | ConvertFrom-Json }
        catch { throw "Invalid dashboard JSON '$($_.FullName)': $($_.Exception.Message)" }
    }
    helm lint $Chart.Directory
    if ($LASTEXITCODE -ne 0) { throw "helm lint failed for '$($Chart.Directory)'." }
    $null = helm template $Chart.Name $Chart.Directory
    if ($LASTEXITCODE -ne 0) { throw "helm template failed for '$($Chart.Directory)'." }
}

function Publish-DeploymentChart {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][pscustomobject]$Chart,
        [Parameter(Mandatory)][string]$ChartRegistry,
        [Parameter(Mandatory)][string]$DeploymentName,
        [Parameter(Mandatory)][string]$Timestamp,
        [string]$Tag,
        [switch]$OnlyCharts
    )

    Connect-HelmRegistry -Registry $ChartRegistry
    $packageDirectory = Join-Path ([IO.Path]::GetTempPath()) "$DeploymentName-chart-$Timestamp"
    New-Item -ItemType Directory -Path $packageDirectory -Force | Out-Null
    try {
        Write-Host "Packaging $($Chart.Name) $($Chart.Version) (appVersion=$Tag) from $($Chart.Path)" -ForegroundColor Cyan
        helm dependency update $Chart.Directory
        if ($LASTEXITCODE -ne 0) { throw "helm dependency update failed." }
        $appVersion = if ($OnlyCharts) { $Chart.Version } else { $Tag }
        helm package $Chart.Directory --version $Chart.Version --app-version $appVersion --destination $packageDirectory
        if ($LASTEXITCODE -ne 0) { throw "helm package failed." }
        $package = Join-Path $packageDirectory "$($Chart.Name)-$($Chart.Version).tgz"
        $ociTarget = "oci://$ChartRegistry/$($Chart.Repository -replace '/[^/]+$', '')"
        Write-Host "Pushing $package -> $ociTarget" -ForegroundColor Cyan
        helm push $package $ociTarget
        if ($LASTEXITCODE -ne 0) { throw "helm push failed." }
    }
    finally {
        Remove-Item $packageDirectory -Recurse -Force -ErrorAction SilentlyContinue
    }
    Write-Host "Pushed chart: ${ChartRegistry}/$($Chart.Repository):$($Chart.Version)" -ForegroundColor Green
}

function Update-DashboardManifest {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Manifest,
        [Parameter(Mandatory)][string]$ManifestRepo,
        [Parameter(Mandatory)][string]$ManifestPath,
        [Parameter(Mandatory)][string]$ChartVersion,
        [Parameter(Mandatory)][string]$DeploymentName,
        [switch]$NoCommit
    )

    $env:DEPLOY_DASHBOARD_CHART_VERSION = $ChartVersion
    Write-Host "Patching $Manifest (targetRevision=$ChartVersion)" -ForegroundColor Cyan
    yq -i '.spec.template.spec.source.targetRevision = strenv(DEPLOY_DASHBOARD_CHART_VERSION)' $Manifest
    if ($LASTEXITCODE -ne 0) { throw "yq failed to patch the dashboard manifest." }

    git -C $ManifestRepo diff --quiet -- $ManifestPath
    if ($LASTEXITCODE -eq 0) {
        Write-Host "No dashboard manifest changes detected - nothing to commit." -ForegroundColor Yellow
        return
    }
    git -C $ManifestRepo --no-pager diff --stat -- $ManifestPath
    if ($NoCommit) {
        Write-Host "Dashboard manifest patched but not committed (-NoCommit)." -ForegroundColor Yellow
        return
    }
    git -C $ManifestRepo add -- $ManifestPath
    git -C $ManifestRepo commit -m "deploy($DeploymentName-dashboards): chart=${ChartVersion}"
    if ($LASTEXITCODE -ne 0) { throw "git commit failed." }
    Push-ManifestRepository -ManifestRepo $ManifestRepo
    Write-Host "Deployed dashboard chart $ChartVersion; ArgoCD will sync the dashboard ApplicationSet." -ForegroundColor Green
}

function Update-ApplicationManifest {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$RepoRoot,
        [Parameter(Mandatory)][string]$Manifest,
        [Parameter(Mandatory)][string]$ManifestRepo,
        [Parameter(Mandatory)][string]$ManifestPath,
        [Parameter(Mandatory)][string]$ImageRepository,
        [Parameter(Mandatory)][string]$Tag,
        [Parameter(Mandatory)][string]$PodAnnotationName,
        [Parameter(Mandatory)][string]$DeploymentName,
        [Parameter(Mandatory)][string]$Timestamp,
        [switch]$Chart,
        [string]$ChartVersion,
        [switch]$NoCommit
    )

    $stamp = "$(Get-DeploymentGitVersion -RepoRoot $RepoRoot)+$Timestamp"
    $patchMessage = "repository=$ImageRepository, tag=$Tag, pullPolicy=Always, deployed-version=$stamp"
    if ($Chart) { $patchMessage += ", targetRevision=$ChartVersion" }
    Write-Host "Patching $Manifest ($patchMessage)" -ForegroundColor Cyan

    $env:DEPLOY_IMG_REPO = $ImageRepository
    $env:DEPLOY_IMG_TAG = $Tag
    $env:DEPLOY_STAMP = $stamp
    $env:DEPLOY_POD_ANNOTATION = $PodAnnotationName
    if ($Chart) { $env:DEPLOY_CHART_VERSION = $ChartVersion }
    yq -i (Get-ManifestPatchExpression -Chart:$Chart) $Manifest
    if ($LASTEXITCODE -ne 0) { throw "yq failed to patch the manifest." }

    git -C $ManifestRepo diff --quiet -- $ManifestPath
    if ($LASTEXITCODE -eq 0) {
        Write-Host "No GitOps changes detected - nothing to commit." -ForegroundColor Yellow
        return
    }
    git -C $ManifestRepo --no-pager diff --stat -- $ManifestPath
    if ($NoCommit) {
        Write-Host "GitOps files patched but not committed (-NoCommit). Review the diff, then commit/push manually." -ForegroundColor Yellow
        return
    }
    git -C $ManifestRepo add -- $ManifestPath
    $commitMessage = if ($Chart) { "deploy($DeploymentName): ${Tag} ${stamp} chart=${ChartVersion}" } else { "deploy($DeploymentName): ${Tag} ${stamp}" }
    git -C $ManifestRepo commit -m $commitMessage
    if ($LASTEXITCODE -ne 0) { throw "git commit failed." }
    Push-ManifestRepository -ManifestRepo $ManifestRepo
    Write-Host "Deployed: ${ImageRepository}:${Tag}; ArgoCD will sync the application." -ForegroundColor Green
}

function Initialize-DeploymentSettings {
    [CmdletBinding()]
    [OutputType([pscustomobject])]
    param(
        [Parameter(Mandatory)][hashtable]$CallerBoundParameters,
        [Parameter(Mandatory)][string]$RepoRoot
    )

    foreach ($setting in $CallerBoundParameters.GetEnumerator()) {
        Set-Variable -Name $setting.Key -Value $setting.Value -Scope 1 -WhatIf:$false
    }
    if (Test-Path $DeployConfigPath) {
        $deployConfig = Import-PowerShellDataFile $DeployConfigPath
        foreach ($setting in $deployConfig.GetEnumerator()) {
            if (-not $CallerBoundParameters.ContainsKey($setting.Key)) {
                Set-Variable -Name $setting.Key -Value $setting.Value -Scope 1 -WhatIf:$false
            }
        }
    }

    $repositoryName = Split-Path $RepoRoot -Leaf
    if ([string]::IsNullOrWhiteSpace($DeploymentName)) {
        Set-Variable -Name DeploymentName -Value $repositoryName.ToLowerInvariant() -Scope 1 -WhatIf:$false
    }
    if ([string]::IsNullOrWhiteSpace($ImageRepository)) {
        Set-Variable -Name ImageRepository -Value "ghcr.io/f2calv/$($repositoryName.ToLowerInvariant())" -Scope 1 -WhatIf:$false
    }
    if (-not $OnlyCharts -and [string]::IsNullOrWhiteSpace($PodAnnotationName)) {
        throw "-PodAnnotationName is required. Supply it explicitly or in '$DeployConfigPath'."
    }
    Set-Variable -Name Rest -Value @(ConvertTo-DeployBuildArguments -Arguments $Rest) -Scope 1 -WhatIf:$false

    if ([string]::IsNullOrWhiteSpace($ManifestRepo)) {
        throw "-ManifestRepo is required. Supply it explicitly or in '$DeployConfigPath'."
    }
    $manifestPath = Resolve-DeploymentManifestPath -OnlyCharts:$OnlyCharts -ManifestPath $ManifestPath `
        -DashboardManifestPath $DashboardManifestPath
    return [pscustomobject]@{
        ManifestPath = $manifestPath
        Manifest     = Join-Path $ManifestRepo $manifestPath
    }
}

function Assert-DeploymentPrerequisites {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Manifest)

    if (-not (Get-Command yq -ErrorAction SilentlyContinue)) {
        throw "yq not found. Install it (e.g. winget install MikeFarah.yq) - required to patch the GitOps manifest."
    }
    if (-not (Test-Path $Manifest)) { throw "GitOps manifest not found at '$Manifest'." }
}

function Invoke-ConfiguredModelDriftCheck {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$RepoRoot,
        [switch]$SkipMigrationCheck,
        [switch]$OnlyCharts,
        [string]$MigrationProject,
        [string]$MigrationContext,
        [string]$MigrationConnectionStringEnvironmentVariable,
        [string]$MigrationConnectionString
    )

    if ($SkipMigrationCheck -or $OnlyCharts) { return }
    Assert-NoModelDrift -RepoRoot $RepoRoot -MigrationProject $MigrationProject `
        -MigrationContext $MigrationContext `
        -MigrationConnectionStringEnvironmentVariable $MigrationConnectionStringEnvironmentVariable `
        -MigrationConnectionString $MigrationConnectionString
}

function Publish-ConfiguredDeploymentChart {
    [CmdletBinding()]
    [OutputType([pscustomobject])]
    param(
        [Parameter(Mandatory)][string]$RepoRoot,
        [Parameter(Mandatory)][string]$Timestamp,
        [switch]$Chart,
        [switch]$OnlyCharts,
        [string]$ChartPath,
        [string]$ChartRepository,
        [string]$DashboardChartPath,
        [string]$DashboardChartRepository,
        [string]$ChartVersion,
        [string]$ChartRegistry,
        [string]$DeploymentName,
        [string]$Tag
    )

    if (-not $Chart -and -not $OnlyCharts) { return $null }
    if (-not (Get-Command helm -ErrorAction SilentlyContinue)) {
        throw "helm not found. Install Helm to use -Chart."
    }
    $deploymentChart = Get-DeploymentChart -RepoRoot $RepoRoot -Timestamp $Timestamp `
        -OnlyCharts:$OnlyCharts -ChartPath $ChartPath -ChartRepository $ChartRepository `
        -DashboardChartPath $DashboardChartPath -DashboardChartRepository $DashboardChartRepository `
        -ChartVersion $ChartVersion
    # Out-Host, not a bare call: helm writes to stdout, which PowerShell folds into this function's
    # output. Without it the caller receives helm's chatter alongside the chart object and reading
    # .Version member-enumerates onto strings.
    if ($OnlyCharts) { Test-DashboardChart -Chart $deploymentChart | Out-Host }
    Publish-DeploymentChart -Chart $deploymentChart -ChartRegistry $ChartRegistry `
        -DeploymentName $DeploymentName -Timestamp $Timestamp -Tag $Tag -OnlyCharts:$OnlyCharts | Out-Host
    return $deploymentChart
}

function Invoke-Deployment {
    [CmdletBinding(SupportsShouldProcess)]
    param([hashtable]$CallerBoundParameters = @{})

    $REPO_ROOT = [IO.Path]::GetFullPath($PSScriptRoot)
    $deployment = Initialize-DeploymentSettings -CallerBoundParameters $CallerBoundParameters -RepoRoot $REPO_ROOT
    $manifestPathToPatch = $deployment.ManifestPath
    $manifest = $deployment.Manifest
    Assert-DeploymentPrerequisites -Manifest $manifest

    if (-not $PSCmdlet.ShouldProcess($manifest, "Build and deploy application artifacts, then patch the GitOps manifest")) { return }

    try {
        Update-ManifestRepository -ManifestRepo $ManifestRepo
        $timestamp = [DateTime]::UtcNow.ToString('yyyyMMddHHmmss')
        Invoke-ConfiguredModelDriftCheck -RepoRoot $REPO_ROOT -SkipMigrationCheck:$SkipMigrationCheck `
            -OnlyCharts:$OnlyCharts -MigrationProject $MigrationProject -MigrationContext $MigrationContext `
            -MigrationConnectionStringEnvironmentVariable $MigrationConnectionStringEnvironmentVariable `
            -MigrationConnectionString $MigrationConnectionString
        Invoke-DeploymentImageBuild -RepoRoot $REPO_ROOT -SkipBuild:$SkipBuild -OnlyCharts:$OnlyCharts `
            -Platforms $Platforms -Tag $Tag -ImageRepository $ImageRepository -Rest $Rest
        $deploymentChart = Publish-ConfiguredDeploymentChart -RepoRoot $REPO_ROOT -Timestamp $timestamp `
            -Chart:$Chart -OnlyCharts:$OnlyCharts -ChartPath $ChartPath -ChartRepository $ChartRepository `
            -DashboardChartPath $DashboardChartPath -DashboardChartRepository $DashboardChartRepository `
            -ChartVersion $ChartVersion -ChartRegistry $ChartRegistry -DeploymentName $DeploymentName -Tag $Tag

        if ($OnlyCharts) {
            Update-DashboardManifest -Manifest $manifest -ManifestRepo $ManifestRepo `
                -ManifestPath $manifestPathToPatch -ChartVersion $deploymentChart.Version `
                -DeploymentName $DeploymentName -NoCommit:$NoCommit
            return
        }
        $resolvedChartVersion = if ($null -eq $deploymentChart) { $null } else { $deploymentChart.Version }
        Update-ApplicationManifest -RepoRoot $REPO_ROOT -Manifest $manifest -ManifestRepo $ManifestRepo `
            -ManifestPath $manifestPathToPatch -ImageRepository $ImageRepository -Tag $Tag `
            -PodAnnotationName $PodAnnotationName -DeploymentName $DeploymentName -Timestamp $timestamp `
            -Chart:$Chart -ChartVersion $resolvedChartVersion -NoCommit:$NoCommit
    }
    finally {
        Remove-LocalDependencies -RepoRoot $REPO_ROOT
    }
}
#endregion Functions

#region Main Execution
if ($MyInvocation.InvocationName -ne '.') {
    try {
        Invoke-Deployment -CallerBoundParameters $PSBoundParameters -WhatIf:$WhatIfPreference
        exit 0
    }
    catch {
        Write-Error -ErrorAction Continue "deploy.ps1 failed: $($_.Exception.Message)"
        exit 1
    }
}
#endregion Main Execution
