<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CasCap.Api.SignalCli" Version="0.11.8" />
    <PackageVersion Include="CasCap.Api.Voice" Version="0.1.3" />
    <PackageVersion Include="CasCap.Api.Voice.Testing" Version="0.1.3" />
    <PackageVersion Include="CasCap.Common.Abstractions" Version="4.14.4" />
    <PackageVersion Include="CasCap.Common.AI" Version="4.14.4" />
    <PackageVersion Include="CasCap.Common.Caching" Version="4.14.4" />
    <PackageVersion Include="CasCap.Common.Hosting.AspNetCore" Version="4.14.4" />
    <PackageVersion Include="CasCap.Common.Configuration" Version="4.14.4" />
    <PackageVersion Include="CasCap.Common.Extensions" Version="4.14.4" />
    <PackageVersion Include="CasCap.Common.Services" Version="4.14.4" />
    <PackageVersion Include="CasCap.Common.Testing" Version="4.14.4" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Google.Protobuf" Version="3.36.2" />
    <PackageVersion Include="Grpc.AspNetCore" Version="2.84.0" />
    <PackageVersion Include="Grpc.Net.Client" Version="2.84.0" />
    <PackageVersion Include="Grpc.Net.ClientFactory" Version="2.84.0" />
    <PackageVersion Include="Grpc.Tools" Version="2.84.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageVersion Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
    <PackageVersion Include="ModelContextProtocol" Version="2.2.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
</Project>
