<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Release'">
    <PackageReference Include="CasCap.Api.SignalCli" />
    <PackageReference Include="CasCap.Common.Abstractions" />
    <PackageReference Include="CasCap.Common.Extensions" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'!='Release'">
    <ProjectReference Include="..\..\..\CasCap.Api.SignalCli\src\CasCap.Api.SignalCli\CasCap.Api.SignalCli.csproj" />
    <ProjectReference Include="..\..\..\CasCap.Common\src\CasCap.Common.Abstractions\CasCap.Common.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\CasCap.Common\src\CasCap.Common.Extensions\CasCap.Common.Extensions.csproj" />
  </ItemGroup>

</Project>
