// <auto-generated />
using System;
using CasCap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CasCap.Data.Migrations
{
    [DbContext(typeof(SignalizrDbContext))]
    partial class SignalizrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CasCap.Data.Entities.InboundMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("PersistedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("persisted_at_utc");

                    b.Property<string>("Sender")
                        .HasColumnType("text")
                        .HasColumnName("sender");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("PersistedAtUtc")
                        .HasDatabaseName("ix_inbound_messages_persisted_at_utc");

                    b.ToTable("inbound_messages", (string)null);
                });

            modelBuilder.Entity("CasCap.Data.Entities.SubscriberCursorEntity", b =>
                {
                    b.Property<string>("SubscriberName")
                        .HasColumnType("text")
                        .HasColumnName("subscriber_name");

                    b.Property<long>("LastAcknowledgedMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_acknowledged_message_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("SubscriberName");

                    b.ToTable("subscriber_cursors", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
